[package]
name = "structenv-derive"
version = "1.0.0"
authors = ["paul <paul@hupaul.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
syn = "1.0.36"
quote = "1.0.7"
proc-macro2 = "1.0.19"